use_frameworks!


target 'ALSShare_Example' do

  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end 
  end

  pod 'ALSShare', :path => '../'

  target 'ALSShare_Tests' do
    inherit! :search_paths

    
  end
end
